---
name: Release
'on':
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Test building image.
        run: docker build -t docker-almalinux9-ansible .

      - name: Run the built image.
        run: docker run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --volume /var/lib/docker/aufs:/var/lib/docker/aufs/ docker-almalinux9-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec -ti test-container ansible --version

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v1

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_TOKEN }}
          password: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest